import { WorkPlace } from './placeTypes';
import cafe1 from '@/assets/cafe-1.jpg';
import cafe2 from '@/assets/cafe-2.jpg';
import cafe3 from '@/assets/cafe-3.jpg';
import cafe4 from '@/assets/cafe-4.jpg';
import cafe5 from '@/assets/cafe-5.jpg';
import cafe6 from '@/assets/cafe-6.jpg';

// Delhi NCR places from curated list + work-friendly spots
const PLACE_TEMPLATES: (Omit<WorkPlace, 'id'> & { offsetLat: number; offsetLng: number })[] = [
  // Cafés / Work spots
  {
    name: 'The Paris Coffeehouse',
    type: 'cafe',
    photos: [cafe2, cafe5],
    amenities: { wifi: true, wifiSpeed: 'fast', powerSockets: true, powerSocketsCount: 'many', quietLevel: 'quiet', seating: 'moderate', outdoorSeating: true, food: true, coffee: true },
    hours: '8am – 10pm',
    rating: 4.5,
    description: 'A charming Parisian-style coffeehouse with excellent pastries and strong WiFi. Great for focused work sessions.',
    lat: 0, lng: 0, offsetLat: 0.004, offsetLng: 0.003,
  },
  {
    name: 'Libertario Coffee Roasters',
    type: 'cafe',
    photos: [cafe1, cafe3],
    amenities: { wifi: true, wifiSpeed: 'fast', powerSockets: true, powerSocketsCount: 'every-seat', quietLevel: 'moderate', seating: 'moderate', outdoorSeating: false, food: true, coffee: true },
    hours: '7:30am – 9pm',
    rating: 4.3,
    description: 'Specialty coffee roasters with a minimalist workspace vibe. Power at every seat and single-origin brews.',
    lat: 0, lng: 0, offsetLat: -0.003, offsetLng: 0.005,
  },
  {
    name: 'Getafix Cafe',
    type: 'cafe',
    photos: [cafe5, cafe2],
    amenities: { wifi: true, wifiSpeed: 'moderate', powerSockets: true, powerSocketsCount: 'few', quietLevel: 'quiet', seating: 'moderate', outdoorSeating: true, food: true, coffee: true },
    hours: '9am – 10pm',
    rating: 4.2,
    description: 'A health-focused café with wholesome bowls, fresh juices, and a calm atmosphere perfect for remote work.',
    lat: 0, lng: 0, offsetLat: 0.006, offsetLng: -0.002,
  },
  {
    name: 'The Big Chill Cafe',
    type: 'cafe',
    photos: [cafe3, cafe6],
    amenities: { wifi: true, wifiSpeed: 'moderate', powerSockets: true, powerSocketsCount: 'few', quietLevel: 'lively', seating: 'plenty', outdoorSeating: false, food: true, coffee: true },
    hours: '11am – 11pm',
    rating: 4.5,
    description: 'Iconic café with legendary cheesecakes and Italian comfort food. Lively atmosphere — great for group brainstorms.',
    lat: 0, lng: 0, offsetLat: -0.005, offsetLng: -0.004,
  },
  {
    name: 'DIGGIN',
    type: 'cafe',
    photos: [cafe4, cafe1],
    amenities: { wifi: true, wifiSpeed: 'moderate', powerSockets: true, powerSocketsCount: 'few', quietLevel: 'moderate', seating: 'plenty', outdoorSeating: true, food: true, coffee: true },
    hours: '10am – 11pm',
    rating: 4.1,
    description: 'A garden café with rustic charm, fairy lights, and Mediterranean fare. The outdoor terrace is perfect for creative sessions.',
    lat: 0, lng: 0, offsetLat: 0.002, offsetLng: -0.006,
  },
  {
    name: 'Delish Mama - Gelato & Cafe',
    type: 'cafe',
    photos: [cafe6, cafe4],
    amenities: { wifi: true, wifiSpeed: 'fast', powerSockets: true, powerSocketsCount: 'many', quietLevel: 'quiet', seating: 'moderate', outdoorSeating: false, food: true, coffee: true },
    hours: '10am – 10pm',
    rating: 4.6,
    description: 'Artisanal gelato meets cozy café. Quiet enough for deep work with excellent desserts for brain fuel.',
    lat: 0, lng: 0, offsetLat: -0.001, offsetLng: 0.007,
  },
  // Restaurants / Food places
  {
    name: 'Paparizza - Trattoria & Bar',
    type: 'other',
    photos: [cafe1, cafe5],
    amenities: { wifi: true, wifiSpeed: 'moderate', powerSockets: false, quietLevel: 'lively', seating: 'plenty', outdoorSeating: true, food: true, coffee: false },
    hours: '12pm – 11:30pm',
    rating: 4.5,
    description: 'Authentic Italian trattoria with wood-fired pizzas and hand-rolled pastas. A neighbourhood favourite.',
    lat: 0, lng: 0, offsetLat: 0.007, offsetLng: 0.001,
  },
  {
    name: 'Si Nonna\'s - Sourdough Pizza',
    type: 'other',
    photos: [cafe3, cafe4],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'lively', seating: 'moderate', outdoorSeating: false, food: true, coffee: false },
    hours: '12pm – 11pm',
    rating: 4.8,
    description: 'Legendary sourdough pizza in GK2. Every pie is a masterpiece — worth the wait.',
    lat: 0, lng: 0, offsetLat: -0.006, offsetLng: 0.003,
  },
  {
    name: 'Sindh Dhaba',
    type: 'other',
    photos: [cafe2, cafe6],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'lively', seating: 'limited', outdoorSeating: true, food: true, coffee: false },
    hours: '10am – 11pm',
    rating: 4.8,
    description: 'Legendary dhaba-style eatery with incredible Sindhi and Punjabi street food. An institution.',
    lat: 0, lng: 0, offsetLat: 0.003, offsetLng: -0.005,
  },
  {
    name: 'Baba Nagpal Corner',
    type: 'other',
    photos: [cafe5, cafe3],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'lively', seating: 'limited', outdoorSeating: false, food: true, coffee: false },
    hours: '11am – 10:30pm',
    rating: 3.9,
    description: 'Cult-favourite street food corner famous for chole bhature and chaap. No-frills, all flavour.',
    lat: 0, lng: 0, offsetLat: -0.004, offsetLng: -0.001,
  },
  {
    name: 'Defence Bakery Since 1962',
    type: 'other',
    photos: [cafe6, cafe1],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'quiet', seating: 'limited', outdoorSeating: false, food: true, coffee: true },
    hours: '8am – 9pm',
    rating: 4.3,
    description: 'Old-school bakery serving warm puffs, biscuits, and bread since 1962. A nostalgic gem.',
    lat: 0, lng: 0, offsetLat: 0.005, offsetLng: 0.006,
  },
  {
    name: 'Hashery - GK2',
    type: 'other',
    photos: [cafe4, cafe2],
    amenities: { wifi: true, wifiSpeed: 'moderate', powerSockets: false, quietLevel: 'moderate', seating: 'moderate', outdoorSeating: false, food: true, coffee: true },
    hours: '10am – 10:30pm',
    rating: 4.5,
    description: 'Trendy dessert spot known for loaded hash browns and Instagram-worthy shakes.',
    lat: 0, lng: 0, offsetLat: -0.002, offsetLng: -0.007,
  },
  {
    name: 'THEOS GK II',
    type: 'other',
    photos: [cafe2, cafe4],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'moderate', seating: 'moderate', outdoorSeating: false, food: true, coffee: true },
    hours: '9am – 9pm',
    rating: 4.5,
    description: 'Artisan bakery with sourdough loaves, croissants, and Greek-inspired bakes. Pure craft.',
    lat: 0, lng: 0, offsetLat: 0.001, offsetLng: -0.003,
  },
  {
    name: 'Sanjha Chulha',
    type: 'other',
    photos: [cafe3, cafe5],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'lively', seating: 'plenty', outdoorSeating: false, food: true, coffee: false },
    hours: '11am – 11pm',
    rating: 3.9,
    description: 'Hearty North Indian fare with butter-soaked naans and smoky tandoori. A family favourite.',
    lat: 0, lng: 0, offsetLat: -0.007, offsetLng: 0.002,
  },
  {
    name: 'Moolchand Parantha & Chur Chur Naan',
    type: 'other',
    photos: [cafe1, cafe6],
    amenities: { wifi: false, powerSockets: false, quietLevel: 'lively', seating: 'limited', outdoorSeating: true, food: true, coffee: false },
    hours: '10am – 12am',
    rating: 3.9,
    description: 'Late-night street food paradise. Crispy paranthas and the iconic chur chur naan since decades.',
    lat: 0, lng: 0, offsetLat: 0.008, offsetLng: -0.001,
  },
];

export function generateDemoPlaces(centerLat = 28.55, centerLng = 77.22): WorkPlace[] {
  return PLACE_TEMPLATES.map((tpl, i) => ({
    id: `place-${i}`,
    name: tpl.name,
    type: tpl.type,
    photos: tpl.photos,
    amenities: tpl.amenities,
    hours: tpl.hours,
    rating: tpl.rating,
    description: tpl.description,
    lat: centerLat + tpl.offsetLat + (Math.random() - 0.5) * 0.002,
    lng: centerLng + tpl.offsetLng + (Math.random() - 0.5) * 0.002,
  }));
}
